name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name:  Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   
    - name: Build & Push to DockerHub
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: oliviermj/php8.2-fpm:latest
      continue-on-error: true
